### PR TITLE
feat: add support for predefined roles as a basis for custom roles

### PR DESCRIPTION
**Pull request by zefdelgadillo**
Adds support for creation of custom roles based on permissions within predefined roles.

### CODE REVIEW

**Comment by zefdelgadillo** [comment]
@morgante @kunalkg11 @bharathkkb - Should we consider automatically excluding permissions that are [unsupported](https://cloud.google.com/iam/docs/custom-roles-permissions-support) for custom roles? If this is merged, it's less clear which unsupported permissions might be in custom role scope given the input is predefined roles.

**Comment by morgante** [comment]
@zefdelgadillo Yes we should automatically filter out permissions that can't be used: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/iam_testable_permissions

**Review by morgante — DISMISSED** [review]

**Comment by zefdelgadillo** [comment]
> @zefdelgadillo Yes we should automatically filter out permissions that can't be used: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/iam_testable_permissions

Thanks. This now excludes unsupported permissions by default using the linked data source.

**Pull request merged**
