### PR TITLE
feat: Add support for conditional for custom role member

### PR DESCRIPTION
**Pull request by ps-occrp**
Add support for conditional for custom role member

### CODE REVIEW

**Comment by imrannayer** [comment]
@ps-occrp thx for the PR. Is it possible if you can follow the same pattern we have for other modules? [See project IAM example](https://github.com/terraform-google-modules/terraform-google-iam/blob/50e81da40515d37bbe7127a6c8dead756ff0da06/modules/projects_iam/variables.tf#L35)

**Comment by imrannayer** [comment]
@ps-occrp can u plz add a condition in [example](https://github.com/terraform-google-modules/terraform-google-iam/blob/master/examples/custom_role_project/main.tf) so we can make it part of integration test?

**Comment by ps-occrp** [comment]
@imrannayer can this be merged?

**Comment by imrannayer** [comment]
@bharathkkb can u plz review? I dont have permission on this repo.

**Comment by ps-occrp** [comment]
@bharathkkb Can this be merged?

**Pull request closed without merging**
